// ============================================================================
// tests/test_quants.cpp — dequantization tests (PLAN §9.3).
//
// Self-contained on purpose: `make test` must stay green with no llama.cpp and
// no model weights present (PLAN §3.4). The truth it checks against is real —
// tests/golden_quants.h holds actual blocks from the Q4_K_XL model paired with
// the exact float bits llama.cpp produced for them, generated by
// tools/quant_oracle.cpp. Re-run that tool after touching quants.h; it does the
// exhaustive comparison (fuzz + every tensor of both blessed models).
// ============================================================================
#include "gguf.h"
#include "ns.h"
#include "quants.h"

#include "golden_quants.h"

#include <cinttypes>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <vector>

using namespace ns;

static int g_checks = 0;
#define CHECK(cond)                                                                 \
    do {                                                                            \
        g_checks++;                                                                 \
        if (!(cond)) {                                                              \
            fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond);         \
            exit(1);                                                                \
        }                                                                           \
    } while (0)

static uint32_t bits_of(float f) {
    uint32_t u;
    memcpy(&u, &f, 4);
    return u;
}

// ---------------------------------------------------------------------------
// The block structs must match ggml's byte layout exactly or every weight in
// the model is misread. sizeof is asserted at compile time in quants.h; this
// re-checks the numbers PLAN §5.3 tabulates, so a mismatch names the format.
// ---------------------------------------------------------------------------
static void test_layouts() {
    CHECK(sizeof(block_q3_K) == 110);
    CHECK(sizeof(block_q4_K) == 144);
    CHECK(sizeof(block_q5_K) == 176);
    CHECK(sizeof(block_q6_K) == 210);
    CHECK(sizeof(block_q8_0) == 34);
    CHECK(sizeof(block_q8_K) == 292);
    CHECK(sizeof(block_iq4_nl) == 18);
    CHECK(sizeof(block_iq4_xs) == 136);
    CHECK(sizeof(block_iq3_s) == 110);
    // and the reader's table must agree with the structs
    CHECK(type_info(NS_Q3_K).bytes == (int64_t)sizeof(block_q3_K));
    CHECK(type_info(NS_Q4_K).bytes == (int64_t)sizeof(block_q4_K));
    CHECK(type_info(NS_Q5_K).bytes == (int64_t)sizeof(block_q5_K));
    CHECK(type_info(NS_Q6_K).bytes == (int64_t)sizeof(block_q6_K));
    CHECK(type_info(NS_Q8_0).bytes == (int64_t)sizeof(block_q8_0));
    CHECK(type_info(NS_IQ4_NL).bytes == (int64_t)sizeof(block_iq4_nl));
    CHECK(type_info(NS_IQ4_XS).bytes == (int64_t)sizeof(block_iq4_xs));
    CHECK(type_info(NS_IQ3_S).bytes == (int64_t)sizeof(block_iq3_s));
    CHECK(type_info(NS_Q4_K).blck == 256 && type_info(NS_Q8_0).blck == 32);
}

// ---------------------------------------------------------------------------
static void test_half_conversion() {
    // exact values, subnormals, and the extremes fp16 can hold
    CHECK(half_to_float(0x0000) == 0.0f);
    CHECK(half_to_float(0x3C00) == 1.0f);
    CHECK(half_to_float(0xBC00) == -1.0f);
    CHECK(half_to_float(0x4000) == 2.0f);
    CHECK(half_to_float(0x3555) == 0.333251953125f);   // nearest fp16 to 1/3
    CHECK(half_to_float(0x0001) == 5.9604644775390625e-8f);  // min subnormal
    CHECK(half_to_float(0x7BFF) == 65504.0f);          // max finite
    CHECK(std::isinf(half_to_float(0x7C00)));
    CHECK(std::isnan(half_to_float(0x7E00)));
    CHECK(bits_of(half_to_float(0x8000)) == 0x80000000u);  // -0.0 keeps its sign
    // bf16 is the top 16 bits of the fp32 pattern
    CHECK(bf16_to_float(0x3F80) == 1.0f);
    CHECK(bf16_to_float(0xC000) == -2.0f);
}

// ---------------------------------------------------------------------------
// get_scale_min_k4 is PLAN §5.3's named off-by-one trap. Check it against the
// bit definition independently of the dequant loops that use it.
// ---------------------------------------------------------------------------
static void test_scale_min_k4() {
    uint8_t q[12];
    for (int i = 0; i < 12; i++) q[i] = (uint8_t)(i * 21 + 7);
    uint8_t d, m;
    for (int j = 0; j < 4; j++) {
        get_scale_min_k4(j, q, &d, &m);
        CHECK(d == (q[j] & 63));
        CHECK(m == (q[j + 4] & 63));
    }
    for (int j = 4; j < 8; j++) {
        get_scale_min_k4(j, q, &d, &m);
        CHECK(d == ((q[j + 4] & 0xF) | ((q[j - 4] >> 6) << 4)));
        CHECK(m == ((q[j + 4] >> 4) | ((q[j] >> 6) << 4)));
    }
    // all 6-bit results must stay in range
    for (int j = 0; j < 8; j++) {
        get_scale_min_k4(j, q, &d, &m);
        CHECK(d < 64 && m < 64);
    }
}

// ---------------------------------------------------------------------------
// Real blocks from the real model vs the exact bits llama.cpp produced.
// ---------------------------------------------------------------------------
static void test_golden() {
    CHECK(k_n_golden_quants == 8);   // all eight quant formats in the blessed files
    for (int i = 0; i < k_n_golden_quants; i++) {
        const GoldenQuant& g = k_golden_quants[i];
        const TypeInfo& ti = type_info(g.type);
        CHECK(g.raw_bytes == (uint64_t)(g.n_elem / ti.blck) * (uint64_t)ti.bytes);

        std::vector<float> out((size_t)g.n_elem, 0.0f);
        CHECK(dequant_row(g.type, g.raw, out.data(), g.n_elem));

        int bad = 0;
        for (int64_t e = 0; e < g.n_elem; e++) {
            if (bits_of(out[e]) != g.expect[e]) {
                if (bad++ < 3) {
                    float want;
                    memcpy(&want, &g.expect[e], 4);
                    fprintf(stderr, "  %s elem %" PRId64 ": ns=%.9g (%08x) llama.cpp=%.9g (%08x)\n",
                            g.type_name, e, out[e], bits_of(out[e]), want, g.expect[e]);
                }
            }
        }
        CHECK(bad == 0);
        // a dequantized weight row should look like weights, not garbage
        double sum = 0.0, absmax = 0.0;
        for (int64_t e = 0; e < g.n_elem; e++) {
            CHECK(std::isfinite(out[e]));
            sum += out[e];
            absmax = std::max(absmax, (double)std::fabs(out[e]));
        }
        CHECK(absmax > 0.0 && absmax < 100.0);
        printf("    %-7s %4" PRId64 " elems from %-26s bit-exact  (mean %+.5f, absmax %.5f)\n",
               g.type_name, g.n_elem, g.tensor, sum / g.n_elem, absmax);
    }
}

// ---------------------------------------------------------------------------
static void test_dispatch() {
    // unsupported types must be refused, not silently mis-decoded
    std::vector<float> out(256, 0.0f);
    std::vector<uint8_t> raw(1024, 0);
    CHECK(!dequant_row(NS_Q2_K, raw.data(), out.data(), 256));
    CHECK(!dequant_row(NS_IQ1_S, raw.data(), out.data(), 256));
    CHECK(!dequant_row(NS_Q4_0, raw.data(), out.data(), 256));
    CHECK(!dequant_row(999, raw.data(), out.data(), 256));
    // the trivial formats round-trip
    const float src[4] = {1.5f, -2.25f, 0.0f, 1e30f};
    float dst[4] = {0, 0, 0, 0};
    CHECK(dequant_row(NS_F32, src, dst, 4));
    CHECK(memcmp(src, dst, sizeof src) == 0);
    const ns_half h[4] = {0x3C00, 0xBC00, 0x0000, 0x7BFF};
    CHECK(dequant_row(NS_F16, h, dst, 4));
    CHECK(dst[0] == 1.0f && dst[1] == -1.0f && dst[2] == 0.0f && dst[3] == 65504.0f);
    // an all-zero quantized block must dequantize to something finite
    CHECK(dequant_row(NS_Q4_K, raw.data(), out.data(), 256));
    for (int i = 0; i < 256; i++) CHECK(out[i] == 0.0f);
}

// ---------------------------------------------------------------------------
// Self-contained coverage for Stage 2's Q8_K x K-quant integer row oracle.
// tools/quant_oracle performs the exact comparison with ggml; this local test
// checks every supported format against the equivalent dequantized dot so the
// paths stay exercised without llama.cpp or model files.
// ---------------------------------------------------------------------------
static void test_q8_K_dots() {
    std::vector<float> zeros(QK_K, 0.0f);
    block_q8_K zero_block;
    memset(&zero_block, 0x7f, sizeof(zero_block));
    quantize_row_q8_K(zeros.data(), &zero_block, QK_K);
    CHECK(zero_block.d == 0.0f);
    for (int i = 0; i < QK_K; i++) CHECK(zero_block.qs[i] == 0);
    for (int i = 0; i < QK_K / 16; i++) CHECK(zero_block.bsums[i] == 0);

    for (int fixture = 0; fixture < k_n_golden_quants; fixture++) {
        const GoldenQuant& golden = k_golden_quants[fixture];
        if (!has_vec_dot_q8_K(golden.type)) continue;
        std::vector<float> activation((size_t)golden.n_elem);
        for (int64_t i = 0; i < golden.n_elem; i++) {
            activation[(size_t)i] =
                0.7f * sinf(0.031f * (float)(i + 1)) +
                0.2f * cosf(0.017f * (float)(i + 3));
        }
        std::vector<block_q8_K> q8((size_t)(golden.n_elem / QK_K));
        quantize_row_q8_K(activation.data(), q8.data(), golden.n_elem);
        for (const block_q8_K& block : q8) {
            for (int group = 0; group < QK_K / 16; group++) {
                int sum = 0;
                for (int j = 0; j < 16; j++) sum += block.qs[group * 16 + j];
                CHECK(block.bsums[group] == sum);
            }
        }

        float integer_result = 0.0f;
        CHECK(vec_dot_q8_K(golden.type, golden.raw, q8.data(), golden.n_elem,
                           &integer_result));
        std::vector<float> weights((size_t)golden.n_elem);
        CHECK(dequant_row(golden.type, golden.raw, weights.data(), golden.n_elem));
        double dequantized_result = 0.0;
        for (int64_t i = 0; i < golden.n_elem; i++) {
            const block_q8_K& block = q8[(size_t)(i / QK_K)];
            const float q8_value = block.d * block.qs[i % QK_K];
            dequantized_result += (double)weights[(size_t)i] * q8_value;
        }
        const double tolerance = 2e-4 * std::max(1.0, fabs(dequantized_result));
        CHECK(fabs((double)integer_result - dequantized_result) <= tolerance);
        CHECK(std::isfinite(integer_result));
    }
    float ignored = 0.0f;
    CHECK(!vec_dot_q8_K(NS_Q8_0, nullptr, &zero_block, QK_K, &ignored));
    CHECK(!vec_dot_q8_K(NS_IQ4_NL, nullptr, &zero_block, QK_K, &ignored));
}

// ---------------------------------------------------------------------------
// If the weights are present, dequantize a whole row of every type actually
// used and sanity-check the distribution. Skipped when the model is absent.
// ---------------------------------------------------------------------------
static void test_real_model_rows() {
    const char* home = getenv("HOME");
    const std::string path =
        std::string(home ? home : "") + "/dev/models/Qwen3.8-27B/Qwen3.8-27B-UD-Q4_K_XL.gguf";
    GgufFile f;
    std::string err;
    if (!f.open(path, &err)) {
        printf("    (model absent — real-row checks skipped, not failed)\n");
        return;
    }
    const Config c = config_from_gguf(f);
    int rows = 0;
    for (const auto& t : f.tensors()) {
        const TypeInfo& ti = type_info(t.type);
        if (t.n_dims != 2 || ti.blck == 1) continue;
        const int64_t k = t.ne[0];          // one row = ne[0] elements
        if (k % ti.blck != 0) continue;
        std::vector<float> row((size_t)k);
        CHECK(dequant_row(t.type, t.data, row.data(), k));
        double absmax = 0.0;
        for (int64_t i = 0; i < k; i++) {
            CHECK(std::isfinite(row[i]));    // no NaN/Inf anywhere in real weights
            absmax = std::max(absmax, (double)std::fabs(row[i]));
        }
        CHECK(absmax > 0.0 && absmax < 100.0);
        rows++;
    }
    printf("    %d tensor rows dequantized from %s: all finite, all in range\n", rows,
           c.name.c_str());
}

int main() {
    printf("  block layouts...\n");
    test_layouts();
    printf("  fp16/bf16 conversion...\n");
    test_half_conversion();
    printf("  get_scale_min_k4...\n");
    test_scale_min_k4();
    printf("  dispatch...\n");
    test_dispatch();
    printf("  Q8_K integer row dots...\n");
    test_q8_K_dots();
    printf("  golden blocks vs llama.cpp...\n");
    test_golden();
    printf("  real model rows...\n");
    test_real_model_rows();
    printf("  OK — %d checks passed\n", g_checks);
    return 0;
}
